/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.24
 * Generated at: 2019-02-03 19:43:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width\", initial-scale=\"1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.css\">\r\n");
      out.write("<title>Infinite Translate Service</title>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write(".cf:before,\r\n");
      out.write(".cf:after {\r\n");
      out.write("    content: \" \"; /* 1 */\r\n");
      out.write("    display: table; /* 2 */\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write(".cf:after {\r\n");
      out.write("    clear: both;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\t.test {\r\n");
      out.write("    resize:none;\r\n");
      out.write("    line-height:30px;\r\n");
      out.write("    width:100%;\r\n");
      out.write("    overflow-y:hidden;\r\n");
      out.write("    width:450px;\r\n");
      out.write("    height:40px;\r\n");
      out.write("    border:1px solid #ccc;\r\n");
      out.write("}\r\n");
      out.write("  \r\n");
      out.write("  \t.jumbotron\t{\r\n");
      out.write("     text-shadow: black 0.1em 0.1em 0.1em;\r\n");
      out.write("     color: white;\r\n");
      out.write("     width: 940px;\r\n");
      out.write("     height: 260px;\r\n");
      out.write("     font-size:30px;\r\n");
      out.write("}\r\n");
      out.write("     .left { float: left }\r\n");
      out.write("     .right { float: rght }\r\n");
      out.write("\r\n");
      out.write(".loader {\r\n");
      out.write("\tposition:absolute;\r\n");
      out.write("\tleft:50%;\r\n");
      out.write("\ttop:50%;\r\n");
      out.write("\tz-index:1;\r\n");
      out.write("\twidth:90px;\r\n");
      out.write("\theight:90px;\r\n");
      out.write("\tmargin:-75px 0 0 -75px;\r\n");
      out.write("\tborder:16px solid #f3f3f3;\r\n");
      out.write("\tborder-radius:50%;\r\n");
      out.write("\tborder-top:16px solid #FF0000;\r\n");
      out.write("\twidth:90px;\r\n");
      out.write("\theight:90px;\r\n");
      out.write("\t-webkit-animation:spin 2s linear infinite;\r\n");
      out.write("\tanimation:spin 2s linear infinite;\r\n");
      out.write("}\r\n");
      out.write("@-webkit-keyframes spin {\r\n");
      out.write("\t0% {\r\n");
      out.write("\t\t-webkit-transform:rotate(0deg);\r\n");
      out.write("\t}\r\n");
      out.write("\t100% {\r\n");
      out.write("\t\t-webkit-transform:rotate(360deg);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("@keyframes spin {\r\n");
      out.write("\t0% {\r\n");
      out.write("\t\ttransform:rotate(0deg);\r\n");
      out.write("\t}\r\n");
      out.write("\t100% {\r\n");
      out.write("\t\ttransform: rotate(360deg);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header>\r\n");
      out.write("    ");

		String userID = null;
/*
		if( session.getAttribute("userID")!= null) {
			userID = (String) session.getAttribute("userID");
		} else {
			response.sendRedirect("./login.jsp");
		}
*/
	
      out.write("\r\n");
      out.write("   <nav class=\"navbar navbar-success\" >\r\n");
      out.write("            <div class=\"navbar-header\">\r\n");
      out.write("               <button type=\"button\" class=\"navbar-toggle collapsed\" \r\n");
      out.write("               \t\tdata-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\" \r\n");
      out.write("               \t\taria-expanded=\"false\">\r\n");
      out.write("                  <span class=\"icon-bar\"></span>\r\n");
      out.write("                  <span class=\"icon-bar\"></span>\r\n");
      out.write("                  <span class=\"icon-bar\"></span>\r\n");
      out.write("               </button>\r\n");
      out.write("                   \r\n");
      out.write("               \r\n");
      out.write("               <a class=\"navbar-brand\" href=\"main.jsp\"><span><img src=\"image/bird.png\" width=\"50\" height=\"50\" alt=\"\">&nbsp&nbsp&nbsp</span>Free Translate</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"collapsed navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("              \r\n");
      out.write("               \r\n");
      out.write("               ");

               		if(userID == null) {		
               
      out.write("\r\n");
      out.write("               \t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("               \t\t<li class=\"dropdown\">\r\n");
      out.write("               \t\t\t<a href=\"#\" class=\"dropdown-toggle\"\r\n");
      out.write("               \t\t\t\tdata-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\"\r\n");
      out.write("               \t\t\t\taria-expanded=\"false\">Menu<span class=\"caret\"></span></a>\r\n");
      out.write("               \t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("               \t\t\t\t<li class=\"active\"><a href=\"login.jsp\">로그인</a></li>\r\n");
      out.write("               \t\t\t\t<li><a href=\"join.jsp\">회원가입</a></li>\r\n");
      out.write("               \t\t\t</ul>\t\t\r\n");
      out.write("               \t\t</li>\r\n");
      out.write("               \t</ul>\r\n");
      out.write("               ");

               		} else {
               
      out.write("\r\n");
      out.write("               \t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("               \t\t<li class=\"dropdown\">\r\n");
      out.write("               \t\t\t<a href=\"#\" class=\"dropdown-toggle\"\r\n");
      out.write("               \t\t\t\tdata-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\"\r\n");
      out.write("               \t\t\t\taria-expanded=\"false\">회원관리<span class=\"caret\"></span></a>\r\n");
      out.write("               \t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("               \t\t\t\t<li class=\"active\"><a href=\"logoutAction.jsp\">로그아웃</a></li>\r\n");
      out.write("               \t\t\t</ul>\t\t\r\n");
      out.write("               \t\t</li>\r\n");
      out.write("               \t</ul>\r\n");
      out.write("               ");

               	}
               
      out.write("\r\n");
      out.write("           </div>\r\n");
      out.write("        <HR>\r\n");
      out.write("      </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("    \r\n");
      out.write("    <section class=\"cf\">\r\n");
      out.write("    <div class=\"col-md-12\" style=\"background-color: #FE2E2E; color:#ffffff\">\r\n");
      out.write("            <h1 class=\"text-center\" style=\"font-size:70px\">글자수 제한없는 번역서비스!</h1>\r\n");
      out.write("            <p class=\"text-center\" style=\"font-size:20px\">Translate the text you entered without limitation on the number of characters.</p>\r\n");
      out.write("            <p class=\"text-center\"><a id=\"transButton\" class=\"btn btn-success btn-lg\" href=\"#\" role=\"button\">번역하기</a></p>       \r\n");
      out.write("    </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    \r\n");
      out.write("    <section class=\"cf\" id='transbar'>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container col-md-12\" >\r\n");
      out.write("\t <div class=\"col-md-6\" style=\"text-align:center\">\r\n");
      out.write("\t <table style=\"margin:0 auto; width: 100%;\">\r\n");
      out.write("\t \t<tr>\r\n");
      out.write("\t \t\t<td>\r\n");
      out.write("\t \t<ul id=\"from\"class=\"nav\">\r\n");
      out.write("               \t\t<li class=\"dropdown\">\r\n");
      out.write("               \t\t\t<a id=\"fromSelect\" href=\"#\" class=\"dropdown-toggle\"\r\n");
      out.write("               \t\t\t\tdata-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\"\r\n");
      out.write("               \t\t\t\taria-expanded=\"false\" data=\"\">언어선택<span class=\"caret\"></span></a>\r\n");
      out.write("               \t\t\t<ul class=\"dropdown-menu\" style=\"min-width:100%; text-align:center\">\r\n");
      out.write("               \t\t\t\t<li><a name=\"ko\">한국어</a></li>\r\n");
      out.write("               \t\t\t\t<li><a name=\"en\">영어</a></li>\r\n");
      out.write("               \t\t\t\t<li><a name=\"ja\">일본어</a></li>\r\n");
      out.write("               \t\t\t\t<!--<li><a name=\"zh-CN\">중국어(간체)</a></li>-->\r\n");
      out.write("               \t\t\t\t<!--<li><a name=\"zh-TW\">중국어(번체)</a></li>-->\r\n");
      out.write("               \t\t\t\t<li><a name=\"es\">스페인어</a></li>\r\n");
      out.write("               \t\t\t\t<li><a name=\"vi\">베트남어</a></li>\r\n");
      out.write("               \t\t\t\t<li><a name=\"th\">태국어</a></li>\r\n");
      out.write("               \t\t\t\t<li><a name=\"id\">인도네시아어</a></li>\r\n");
      out.write("               \t\t\t</ul>\r\n");
      out.write("               \t\t</li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        \t</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("        <td>\r\n");
      out.write("      \t<textarea id=\"inputText\" class=\"test\" style=\"width: 100%;\" onkeyup=\"this.style.height='26px'; this.style.height = this.scrollHeight + 'px'; transbarSize()\" placeholder=\"Text를 입력해주세요.\" ></textarea>\r\n");
      out.write("      \t</td>\r\n");
      out.write("      \t</tr>\r\n");
      out.write("     </table>\r\n");
      out.write("     </div>\r\n");
      out.write("\t  \t\r\n");
      out.write("\t  \t\r\n");
      out.write("\t <div class=\"col-md-6\" style=\"text-align:center\">\r\n");
      out.write("\t <table style=\"margin:0 auto; width: 100%;\">\r\n");
      out.write("\t \t<tr>\r\n");
      out.write("\t \t\t<td>\r\n");
      out.write("\t \t\t<ul id=\"to\" class=\"nav\">\r\n");
      out.write("               \t\t<li class=\"dropdown\">\r\n");
      out.write("               \t\t\t<a id=\"toSelect\" href=\"#\" class=\"dropdown-toggle\"\r\n");
      out.write("               \t\t\t\tdata-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\"\r\n");
      out.write("               \t\t\t\taria-expanded=\"false\" data=\"\">언어 선택<span class=\"caret\"></span></a>\r\n");
      out.write("               \t\t\t<ul class=\"dropdown-menu\" style=\"min-width:100%; text-align:center\">\r\n");
      out.write("               \t\t\t\t<li><a name=\"ko\">한국어</a></li>\r\n");
      out.write("               \t\t\t\t<li><a name=\"en\">영어</a></li>\r\n");
      out.write("               \t\t\t\t<li><a name=\"ja\">일본어</a></li>\r\n");
      out.write("               \t\t\t\t<li><a name=\"zh-CN\">중국어(간체)</a></li>\r\n");
      out.write("               \t\t\t\t<li><a name=\"zh-TW\">중국어(번체)</a></li>\r\n");
      out.write("               \t\t\t\t<li><a name=\"es\">스페인어</a></li>\r\n");
      out.write("               \t\t\t\t<li><a name=\"vi\">베트남어</a></li>\r\n");
      out.write("               \t\t\t\t<li><a name=\"th\">태국어</a></li>\r\n");
      out.write("               \t\t\t\t<li><a name=\"id\">인도네시아어</a></li>\r\n");
      out.write("               \t\t\t\t\r\n");
      out.write("               \t\t\t</ul>\r\n");
      out.write("               \t\t</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("         \t<td>\r\n");
      out.write("\t\t\t<pre id=\"result\" style=\"width:100%; white-space: pre-wrap;\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</pre>\r\n");
      out.write("\t\t\t<div class=\"loader\" style=\"display:none\">\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t \t</td>\r\n");
      out.write("\t \t</tr>\r\n");
      out.write("\t</table>\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("    </section>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("      <footer style=\"background-color: #FE2E2E; color:#ffffff\">\r\n");
      out.write("         <div class=\"container\">\r\n");
      out.write("            <div class=\"row\"> <!--row의 총공간은 12로 2씨 나눠서 6개공간 쓴다 -->\r\n");
      out.write("               <div class=\"col-sm-2\" style=\"text-align: center;\"><h5>Copyrigth &copy; 2017</h5><h5>이수지 > 배수지</h5></div>\r\n");
      out.write("               <div class=\"col-sm-4\"><h4>서비스 소개</h4><p>글자수에 제한없이 번역이 가능하며 입력하는 만큼 입력창의 길이가 늘어납니다!</p></div>\r\n");
      out.write("               <div class=\"col-sm-2\"><h4 style=\"text-align: center;\">다른번역 서비스</h4>\r\n");
      out.write("                  <div class=\"list-group\">\r\n");
      out.write("                     <a href=\"https://translate.google.co.kr/?hl=ko\" class=\"list-group-item\">구글번역</a>\r\n");
      out.write("                     <a href=\"https://papago.naver.com/\" class=\"list-group-item\">파파고</a>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"col-sm-2\"><h4 style=\"text-align: center;\">SNS</h4>\r\n");
      out.write("                  <div class=\"list-group\">\r\n");
      out.write("                     <a href=\"https://www.facebook.com\" class=\"list-group-item\">페이스북</a>\r\n");
      out.write("                     <a href=\"https://www.youtube.com\"  class=\"list-group-item\">유튜브</a>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"col-sm-2\"><h4 style=\"text-align: center;\"><span class=\"glyphicon glyphicon-ok\"></span>&nbsp;Free Translate\t</h4></div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </footer><HR>\r\n");
      out.write("      \r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/bootstrap.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tvar from=\"en\";\r\n");
      out.write("\tvar to=\"ko\";\r\n");
      out.write("\r\n");
      out.write("\t$('#from li > a').on('click', function() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#fromSelect').attr(\"data\", $(this).attr(\"name\"));\r\n");
      out.write("\t\t$('#fromSelect').html($(this).text());\r\n");
      out.write("\t\tfrom = $(this).attr(\"name\");\r\n");
      out.write("\t    \r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$('#to li > a').on('click', function() { \r\n");
      out.write("\r\n");
      out.write("\t\t$('#toSelect').attr(\"data\", $(this).attr(\"name\"))\r\n");
      out.write("\t\t$('#toSelect').html($(this).text());\r\n");
      out.write("\t    \tto = $(this).attr(\"name\");\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tfunction transbarSize() {\r\n");
      out.write("\t    var inputText = $(\"#inputText\").css(\"height\").substring(0,$(\"#inputText\").css(\"height\").indexOf(\"px\")) * 1;\r\n");
      out.write("\t    var result = $(\"#result\").css(\"height\").substring(0,$(\"#result\").css(\"height\").indexOf(\"px\")) * 1;\r\n");
      out.write("\t    var div = $(\"#transbar\");\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\t$(\"#transButton\").click(function(){  \r\n");
      out.write("\t    \r\n");
      out.write("      \t    var str = $(\"#inputText\").val();\r\n");
      out.write("\r\n");
      out.write("\t\tstr = str.replace(/(?:\\\\)/g, '\\\\\\\\');\r\n");
      out.write("                str = str.replace(/(?:\\t)/g, '\\\\t');\r\n");
      out.write("                str = str.replace(/(?:\\v)/g, '\\\\v');\r\n");
      out.write("                str = str.replace(/(?:\\\")/g, \"\\\\\\\\\\\\\\\"\");\r\n");
      out.write("//                str = str.replace(/(?:\\')/g, '\\\\\\\\\\\\\\\\\\'');\r\n");
      out.write("                str = str.replace(/(?:\\r\\n|\\r|\\n)/g, '\\\\n');\r\n");
      out.write("\r\n");
      out.write("\t    var data = encodeURI(str);\r\n");
      out.write("\t    var url = \"./translate.jsp\";  \r\n");
      out.write("\t    var params = \"from=\" + from + \"&to=\" + to + \"&data=\" + data;\r\n");
      out.write("\t  \r\n");
      out.write("\t    $.ajax({      \r\n");
      out.write("\t        type:\"POST\",  \r\n");
      out.write("\t        url:url,      \r\n");
      out.write("\t        data:params,    \r\n");
      out.write("\t\tbeforeSend:function(){\r\n");
      out.write("\t\t\tvar loader = $(\"div.loader\"); \r\n");
      out.write("\t                loader.css(\"display\",\"block\"); \r\n");
      out.write("\t\t},\r\n");
      out.write("\t        success:function(args){  \r\n");
      out.write("\t\t    console.log(args); \r\n");
      out.write("\t            $(\"#result\").html(args);      \r\n");
      out.write("\t        },   \r\n");
      out.write("\t        complete:function(){\r\n");
      out.write("\t\t\tvar loader = $(\"div.loader\"); \r\n");
      out.write("                        loader.css(\"display\",\"none\");\r\n");
      out.write("\t\t},  \r\n");
      out.write("\t        error:function(e){  \r\n");
      out.write("\t            alert(e.responseText);  \r\n");
      out.write("\t        }  \r\n");
      out.write("\t    });  \r\n");
      out.write("\t      \r\n");
      out.write("\t});  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
